### ISSUE TITLE
Download PVoutput.org data from Italy

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVItaly#4]
## Detailed Description
Download data from Italien sites from pvoutput.org. 
Good to start with data from 2020 to now. 

## Context
- Useful for training our model
- Metadata has already been downloaded by @jacobbieker (could you add where this has been downloaded)

## Possible Implementation
Find out more information from @JackKelly how data has been previously downloaded

**Comment by jacobbieker** [comment]
The metadata and sites are at  '/mnt/storage_ssd_4tb/' on Donatello in CSV files, split by country.

**Comment by peterdudfield** [comment]
Thanks @jacob, would you be able to upload your API key to 1password?

**Comment by jacobbieker** [comment]
> Thanks @jacob, would you be able to upload your API key to 1password? 

Yep, I'll do that soon

**Comment by JackKelly** [comment]
I think I used this script to download PV timeseries data from PVOutput.org: https://github.com/openclimatefix/pvoutput/blob/main/examples/download_pv_timeseries.ipynb

I'd maybe advocate for downloading data from, say, 2014 onwards. It would be really nice to be able to build up a multi-year dataset.

**Comment by peterdudfield** [comment]
@JackKelly does this use the metadata Jacob has already downloaded? Or was this the one where it searched for various ites using a grid search?

**Comment by JackKelly** [comment]
hehe, good question... I must admit it feels like a lifetime ago that I ran that script.... but, briefly skim-reading the code, I'm pretty sure that script needs to be given the list of PV systems you want to download (in `INPUT_PV_LIST_FILENAME`).

**Comment by peterdudfield** [comment]
thanks @JackKelly .

**Comment by JackKelly** [comment]
Sorry, I'm a bit behind... but... was there a plan to download _all_ PVOutput.org data? Is there some urgency to getting data for just Italy?

**Comment by peterdudfield** [comment]
Yea, a Pilot project for SV - they would like some results before 12th November.

Thats why i put these tasks in here - #2  

We should download lots more data, but Italy should be prioritised

**Comment by peterdudfield** [comment]
Hi @jacobbieker. Would you be able to upload the password and login to pvoutput.org to onepassword. This means I can log in and get the system_id number. Ive tried pulling some data, and I think this information is need. 

Thanks

**Comment by jacobbieker** [comment]
Hi, I've added that now.

**Comment by peterdudfield** [comment]
This is done now, data is saved to 'gs://solar-pv-nowcasting-data/PV/PVOutput.org/Italy'
