### ISSUE TITLE
Downloaded NWP data for PVsites in Italy

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVItaly#5]
## Detailed Description
Get NWP ERA5 data for specific sites at Italy. Get forecasts from 0 to 12 hours. 
Get the following variables
- TODO from https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=form

## Context
need NWP data for training ML model for sites in italy

**Comment by JackKelly** [comment]
I might be confused but it's worth noting that ERA5 isn't a forecast: it's a reanalysis. It attempts to estimate the state of the weather system in the past. It doesn't attempt to forecast the future :)

**Comment by peterdudfield** [comment]
Hi @JackKelly . This could be my mistake, I knew it was reanalysis, but I thought it made a forecast too. 

@jacobbieker also mentioned GFS, but it was only available from 2021 April onwards. Despite this lack of data, perhaps this is still the best option

**Comment by jacobbieker** [comment]
We can get older gfs data, but they changed the model significantly in April 2021, so might be quite different for the first few months of the year which is my concern.

**Comment by peterdudfield** [comment]
How easy it is to get the GFS data?

**Comment by jacobbieker** [comment]
> How easy it is to get the GFS data?

Quite easy, it's available publicly, it'll take a bit to download and process from grib to zarr, so a bit more difficult than the era5 but not by much

**Comment by peterdudfield** [comment]
Thanks @jacobbieker. Feels like we should go for GFS, or atleast try it. Do you have an API link for this? Just so I could try getting the data

**Comment by jacobbieker** [comment]
The GFS data is also only at 3 hourly resolution, vs hourly for era5, we could try getting historical ECMWF forecasts from TIGGE, but we might not have enough time.

**Comment by jacobbieker** [comment]
The GFS is here https://rda.ucar.edu/datasets/ds084.1/ and I think I put a script to download, convert and upload to HF on our HF script repo

**Comment by peterdudfield** [comment]
> The GFS is here https://rda.ucar.edu/datasets/ds084.1/ and I think I put a script to download, convert and upload to HF on our HF script repo

Do you have a link for the that script?

**Comment by jacobbieker** [comment]
> > The GFS is here https://rda.ucar.edu/datasets/ds084.1/ and I think I put a script to download, convert and upload to HF on our HF script repo
> 
> Do you have a link for the that script?

https://github.com/openclimatefix/hf-data-scripts/blob/main/download_combine_upload_gfs.py

**Comment by peterdudfield** [comment]
Lets start with these features

- wind speed
- Downward longwave radiation flux - ground
- Air temperature at 1 meter above surface in Kelvin.
- Precipitation rate at the surface in kg/m^2/s.

**Comment by peterdudfield** [comment]
@jacobbieker started to downloaded the files using this [file](https://github.com/openclimatefix/hf-data-scripts/blob/main/download_combine_upload_gfs_accumulation.py) onto his laptop

Its being uplaoded to mnt/storage_ssd_8tb/GFS on leonardo
Some are being uploaded to gs://solar-pv-nowcasting-data/NWP/GFS

**Comment by carderne** [comment]
Done in #8 and #10
